export { default as NavigationBar } from "./NavigationBar/NavigationBar"
export { default as Hero } from "./Hero/Hero"
export { default as Solution } from "./Solution/Solution"
export { default as Service } from "./Service/Service"
export { default as News } from "./News/News"
export { default as Footer } from "./Footer/Footer"